services:
  - type: web
    name: mobilier-app
    env: php
    buildCommand: |
      # Install PHP dependencies
      composer install --optimize-autoloader --no-dev

      # Install Node.js dependencies
      npm install

      # Build frontend assets (React + Tailwind)
      npm run build

      # Generate application key if not set
      php artisan key:generate --force

      # Cache configuration for better performance
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

      # Run database migrations
      php artisan migrate --force

      # Seed database if needed (optional - remove if not needed in production)
      php artisan db:seed --force

      # Create storage link for file uploads
      php artisan storage:link

    startCommand: |
      # Start the PHP server
      php artisan serve --host=0.0.0.0 --port=$PORT

    plan: starter

    envVars:
      - key: APP_NAME
        value: "Mobilier App"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: mobilier-app
          property: url
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: BROADCAST_DRIVER
        value: log
      - key: VITE_APP_NAME
        value: "Mobilier App"
      - key: SUPABASE_URL
        value: https://fzenqbtkhhowekutajen.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzI3MTcsImV4cCI6MjA2NjgwODcxN30.Fm2SHsuvMhpT9mPwqSfVR4zZExQGe9uOHQyKfQAJ_w4
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTIzMjcxNywiZXhwIjoyMDY2ODA4NzE3fQ.bxiq2qY3Mt07TWUbyNl3MoXyVWoI0l_erwVYUYdeC6g
      - key: VITE_SUPABASE_URL
        value: https://fzenqbtkhhowekutajen.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzI3MTcsImV4cCI6MjA2NjgwODcxN30.Fm2SHsuvMhpT9mPwqSfVR4zZExQGe9uOHQyKfQAJ_w4
