services:
  - type: web
    name: mobilier-app
    env: php
    buildCommand: |
      # Install PHP dependencies
      composer install --optimize-autoloader --no-dev

      # Install Node.js dependencies with clean cache
      npm cache clean --force
      npm ci

      # Clear any existing build files
      rm -rf public/build
      mkdir -p public/build

      # Set Node environment and build assets
      export NODE_ENV=production
      export NODE_OPTIONS="--max-old-space-size=1024"
      
      # Build frontend assets with detailed logging
      echo "🔨 Building Vite assets..."
      npm run build -- --mode production
      
      # Verify build completed successfully
      echo "📁 Checking build directory..."
      ls -la public/build/
      
      if [ -f "public/build/manifest.json" ]; then
        echo "✅ Vite manifest created successfully"
        cat public/build/manifest.json
      else
        echo "❌ Vite manifest missing - attempting fallback build"
        # Try alternative build
        npx vite build --mode production
        ls -la public/build/
      fi

      # Set proper permissions
      chmod -R 755 public/build

      # Generate Laravel optimizations
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

      # Run database migrations
      php artisan migrate --force

      # Create storage symlink
      php artisan storage:link

      echo "🚀 Build completed successfully!"

    startCommand: |
      php artisan serve --host=0.0.0.0 --port=$PORT

    plan: starter

    envVars:
      - key: APP_NAME
        value: "Mobilier App"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: mobilier-app
          property: url
      - key: ASSET_URL
        fromService:
          type: web
          name: mobilier-app
          property: url
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.fzenqbtkhhowekutajen.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      # DB_PASSWORD needs to be set manually in Render dashboard
      - key: DB_PASSWORD
       value: Wa2020lid
      - key: APP_KEY
        value: base64:etnxLIDiqysgXpnnCtZvVFsIQfWUxaigZWAliqJG+Qw=
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: BROADCAST_DRIVER
        value: log
      - key: VITE_APP_NAME
        value: "Mobilier App"
      - key: FORCE_HTTPS
        value: true
      - key: SUPABASE_URL
        value: https://fzenqbtkhhowekutajen.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzI3MTcsImV4cCI6MjA2NjgwODcxN30.Fm2SHsuvMhpT9mPwqSfVR4zZExQGe9uOHQyKfQAJ_w4
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTIzMjcxNywiZXhwIjoyMDY2ODA4NzE3fQ.bxiq2qY3Mt07TWUbyNl3MoXyVWoI0l_erwVYUYdeC6g
      - key: VITE_SUPABASE_URL
        value: https://fzenqbtkhhowekutajen.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzI3MTcsImV4cCI6MjA2NjgwODcxN30.Fm2SHsuvMhpT9mPwqSfVR4zZExQGe9uOHQyKfQAJ_w4
