services:
  - type: web
    name: mobilier-app
    env: php
    buildCommand: |
      # Install dependencies
      composer install --optimize-autoloader --no-dev
      npm ci

      # Clear any existing build files
      rm -rf public/build

      # Build frontend assets with verbose output
      NODE_ENV=production npm run build

      # Verify build files were created
      ls -la public/build/
      [ -f public/build/manifest.json ] && echo "✅ Vite manifest created" || echo "❌ Vite manifest missing"

      # Set proper permissions
      chmod -R 755 public/build

      # Generate key and optimize
      php artisan key:generate --force
      php artisan optimize:clear
      php artisan optimize

      # Run migrations
      php artisan migrate --force

      # Create storage link
      php artisan storage:link

    startCommand: |
      php artisan serve --host=0.0.0.0 --port=$PORT

    plan: starter

    envVars:
      - key: APP_NAME
        value: "Mobilier App"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: mobilier-app
          property: url
      - key: ASSET_URL
        fromService:
          type: web
          name: mobilier-app
          property: url
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.fzenqbtkhhowekutajen.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      # DB_PASSWORD needs to be set manually in Render dashboard
      # - key: DB_PASSWORD
      #   value: YOUR_SUPABASE_DB_PASSWORD
      - key: APP_KEY
        value: base64:etnxLIDiqysgXpnnCtZvVFsIQfWUxaigZWAliqJG+Qw=
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: BROADCAST_DRIVER
        value: log
      - key: VITE_APP_NAME
        value: "Mobilier App"
      - key: FORCE_HTTPS
        value: true
      - key: SUPABASE_URL
        value: https://fzenqbtkhhowekutajen.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzI3MTcsImV4cCI6MjA2NjgwODcxN30.Fm2SHsuvMhpT9mPwqSfVR4zZExQGe9uOHQyKfQAJ_w4
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTIzMjcxNywiZXhwIjoyMDY2ODA4NzE3fQ.bxiq2qY3Mt07TWUbyNl3MoXyVWoI0l_erwVYUYdeC6g
      - key: VITE_SUPABASE_URL
        value: https://fzenqbtkhhowekutajen.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZW5xYnRraGhvd2VrdXRhamVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzI3MTcsImV4cCI6MjA2NjgwODcxN30.Fm2SHsuvMhpT9mPwqSfVR4zZExQGe9uOHQyKfQAJ_w4
